<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; //Use the DB Facades pattern

class GaspriceSeeder extends Seeder
{
    public function run()
    {
        // Insert test data on the gasoline_prices table
        DB::table('gasoline_prices')->insert([
            [
                'id' => '587fbd68edfe99480a072f14',
                'calle' => 'Av. Adolfo López Mateos No. 1604  Col. Melchor Ocampo  Juárez',
                'rfc' => 'DGA930823KD3',
                'razonsocial' => 'DÍAZ GAS  S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.784Z',
                'numeropermiso' => 'PL/760/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2041',
                'longitude' => '-106.4514',
                'latitude' => '31.71947',
                'codigopostal' => '32380',
                'colonia' => null,
                'municipio' => 'Juárez',
                'estado' => 'Chihuahua',
                'regular' => 15.71,
                'premium' => 17.93,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f15',
                'calle' => 'Ricardo Flores Magon No. 950  Col. Huentitan el Alto  Guadalajara',
                'rfc' => 'CEX9809213U5',
                'razonsocial' => 'COMBU-EXPRESS  S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.805Z',
                'numeropermiso' => 'PL/825/EXP/ES/2015',
                'fechaaplicacion' => '09/01/2017 09 => 04 => 00 a. m.',
                'permisoid' => '2042',
                'longitude' => '-103.3042',
                'latitude' => '20.71413',
                'codigopostal' => '44390',
                'colonia' => null,
                'municipio' => 'Guadalajara',
                'estado' => 'Jalisco',
                'regular' => 16.52,
                'premium' => 18.4,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f16',
                'calle' => 'Blvd. Harold R. Pape No.2103-A  Col. Jardines De Guadalupe',
                'rfc' => 'ABE980120EV4',
                'razonsocial' => 'AUTOSERVICIO BERLANGA S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.806Z',
                'numeropermiso' => 'PL/797/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2050',
                'longitude' => '-101.4189',
                'latitude' => '26.92554',
                'codigopostal' => '25736',
                'colonia' => null,
                'municipio' => 'Monclova',
                'estado' => 'Coahuila de Zaragoza',
                'regular' => 16.03,
                'premium' => 17.8,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f17',
                'calle' => 'Carretera San Blas-Santa Cruz km. 13  Aticama  Municipio de San Blas',
                'rfc' => 'GOC9303301F4',
                'razonsocial' => 'GRUPO OCTANO  S.A. DE C.V',
                'date_insert' => '2017-01-18T19 => 09 => 26.806Z',
                'numeropermiso' => 'PL/366/EXP/ES/2015',
                'fechaaplicacion' => '07/01/2017 01 => 40 => 00 p. m.',
                'permisoid' => '2052',
                'longitude' => '-105.1947',
                'latitude' => '21.4739',
                'codigopostal' => '63740',
                'colonia' => null,
                'municipio' => 'San Blas',
                'estado' => 'Nayarit',
                'regular' => 16.33,
                'premium' => null,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f18',
                'calle' => 'Av. Gustavo Baz  S/N  San Pedro Barrientos',
                'rfc' => 'SSE980310JG6',
                'razonsocial' => 'Servicio Sevilla  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.808Z',
                'numeropermiso' => 'PL/868/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2054',
                'longitude' => '-99.1973',
                'latitude' => '19.58616',
                'codigopostal' => '54010',
                'colonia' => null,
                'municipio' => 'Tlalnepantla de Baz',
                'estado' => 'Mexico',
                'regular' => 16.27,
                'premium' => 18.14,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f19',
                'calle' => 'Carretera Internacional Km. 1170 S/N  Barrio de Fátima  San Cristóbal de la Casas',
                'rfc' => 'GHU071016HE1',
                'razonsocial' => 'GASOLINERA HUITEPEC  S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.808Z',
                'numeropermiso' => 'PL/887/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2056',
                'longitude' => '-92.65437',
                'latitude' => '16.73187',
                'codigopostal' => '29264',
                'colonia' => null,
                'municipio' => 'San Cristóbal de las Casas',
                'estado' => 'Chiapas',
                'regular' => 15.73,
                'premium' => 17.50,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f1a',
                'calle' => 'Prol. Pino Suárez 126  Villas de San Francisco  Durango',
                'rfc' => 'SSM091209SP5',
                'razonsocial' => 'SUPER SERVICIO MIVASA  S. A. DE C. V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.810Z',
                'numeropermiso' => 'PL/890/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2058',
                'longitude' => '-104.6217',
                'latitude' => '24.02956',
                'codigopostal' => '34287',
                'colonia' => null,
                'municipio' => 'Durango',
                'estado' => 'Durango',
                'regular' => 16.27,
                'premium' => 18.04,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f1b',
                'calle' => 'Nogales 4900 Frac Atenas Chihuahua ',
                'rfc' => 'CLA030213925',
                'razonsocial' => 'COMBUSTIBLES Y LUBRICANTES ATENAS S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.810Z',
                'numeropermiso' => 'PL/795/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2060',
                'longitude' => '-106.1008',
                'latitude' => '28.73367',
                'codigopostal' => '31104',
                'colonia' => null,
                'municipio' => 'Chihuahua',
                'estado' => 'Chihuahua',
                'regular' => 16.12,
                'premium' => 18.08,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f1c',
                'calle' => 'Carretera Tijuana-Rosarito No. 9311-1B Col. Francisco Zarco',
                'rfc' => 'BOP970701TK2',
                'razonsocial' => 'BECKTROP OPERADORA S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.813Z',
                'numeropermiso' => 'PL/708/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2062',
                'longitude' => '-117.0249',
                'latitude' => '32.45102',
                'codigopostal' => '22660',
                'colonia' => null,
                'municipio' => 'Tijuana',
                'estado' => 'Baja California',
                'regular' => 16.04,
                'premium' => null,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f1d',
                'calle' => 'Carretera Federal Manzanillo Colima Km 307+500  El Colomo',
                'rfc' => 'RAM0402269N0',
                'razonsocial' => 'RAMCAL S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.815Z',
                'numeropermiso' => 'PL/689/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2070',
                'longitude' => '-104.2109',
                'latitude' => '19.03549',
                'codigopostal' => '28800',
                'colonia' => null,
                'municipio' => 'Manzanillo',
                'estado' => 'Colima',
                'regular' => 15.95,
                'premium' => 17.71,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f1e',
                'calle' => 'Calzada de Tlalpan No. 2803  Col. Pueblo de Pablo Tepetlalpa  Coyoacán',
                'rfc' => 'GAS971104DC7',
                'razonsocial' => 'Gasomac S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.815Z',
                'numeropermiso' => 'PL/650/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2071',
                'longitude' => '-99.13844',
                'latitude' => '19.3231',
                'codigopostal' => '4620',
                'colonia' => null,
                'municipio' => 'Coyoacán',
                'estado' => 'Ciudad de México',
                'regular' => 16.32,
                'premium' => 18.19,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f1f',
                'calle' => 'Avenida Periférico Sur número 5550  Colonia Pedregal de Carrasco  Delegación Coyoacán',
                'rfc' => 'API981020E64',
                'razonsocial' => 'Autoconsumo Los Pinos  S.A de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.816Z',
                'numeropermiso' => 'PL/866/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2072',
                'longitude' => '-99.16505',
                'latitude' => '19.30205',
                'codigopostal' => '4700',
                'colonia' => null,
                'municipio' => 'Coyoacán',
                'estado' => 'Ciudad de México',
                'regular' => 16.32,
                'premium' => 18.19,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f20',
                'calle' => 'Carretera Estatal a Gral. Cepeda No. 2731  S/C  Saltillo',
                'rfc' => 'sep040310ru8',
                'razonsocial' => 'SERVICIOS ENERGÉTICOS PLAZA INDUSTRIAL S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.816Z',
                'numeropermiso' => 'PL/764/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2074',
                'longitude' => '-101.1169',
                'latitude' => '25.2563',
                'codigopostal' => '25324',
                'colonia' => null,
                'municipio' => 'Saltillo',
                'estado' => 'Coahuila de Zaragoza',
                'regular' => 15.98,
                'premium' => 17.75,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f21',
                'calle' => 'Libramiento Sur Oriente No. 3430 Col. Cerro Hueco',
                'rfc' => 'OLE110824821',
                'razonsocial' => 'OLEUM GAS S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.821Z',
                'numeropermiso' => 'PL/754/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2076',
                'longitude' => '-93.09296',
                'latitude' => '16.73384',
                'codigopostal' => '29094',
                'colonia' => null,
                'municipio' => 'Tuxtla Gutiérrez',
                'estado' => 'Chiapas',
                'regular' => 15.73,
                'premium' => 17.5,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f22',
                'calle' => 'Carr.  Villa del Carbón No. 332  Col. Villa Nicolás Romero  Villa Nicolás Romero Centro',
                'rfc' => 'GCI9904202C8',
                'razonsocial' => 'Gasolinería Cid  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.821Z',
                'numeropermiso' => 'PL/823/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2078',
                'longitude' => '-99.36308',
                'latitude' => '19.64046',
                'codigopostal' => '54400',
                'colonia' => null,
                'municipio' => 'Nicolás Romero',
                'estado' => 'México',
                'regular' => 16.27,
                'premium' => 18.14,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f23',
                'calle' => 'Carretera 57 Km 16+800  Colonia Central  Nextlalpan',
                'rfc' => 'GPE121210ER8',
                'razonsocial' => 'Gasolinería Perseo  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.823Z',
                'numeropermiso' => 'PL/627/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2079',
                'longitude' => '-99.11606',
                'latitude' => '19.74912',
                'codigopostal' => '55790',
                'colonia' => null,
                'municipio' => 'Nextlalpan',
                'estado' => 'México',
                'regular' => 16.32,
                'premium' => 18.2,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f24',
                'calle' => 'Avenida Convención 1914 Norte No.1902  Col. Buenos Aires',
                'rfc' => 'SAV6903133T7',
                'razonsocial' => 'SERVICIO AVENIDA  S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.823Z',
                'numeropermiso' => 'PL/724/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2084',
                'longitude' => '-102.3053',
                'latitude' => '21.89668',
                'codigopostal' => '20020',
                'colonia' => null,
                'municipio' => 'Aguascalientes',
                'estado' => 'Aguascalientes',
                'regular' => 16.16,
                'premium' => 17.93,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f25',
                'calle' => 'Tiburón 1  Fondeport  Manzanillo',
                'rfc' => 'SOC070606PG2',
                'razonsocial' => 'Socombumex  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.824Z',
                'numeropermiso' => 'PL/690/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2089',
                'longitude' => '-104.288',
                'latitude' => '19.07791',
                'codigopostal' => '28219',
                'colonia' => null,
                'municipio' => 'Manzanillo',
                'estado' => 'Colima',
                'regular' => 15.95,
                'premium' => 17.71,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f26',
                'calle' => 'Avenida de las Bombas s/n Colonia San Isidro Atlautenco',
                'rfc' => 'GSE100226CI6',
                'razonsocial' => 'Gasolinería Segovia S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.825Z',
                'numeropermiso' => 'PL/699/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2090',
                'longitude' => '-98.99508',
                'latitude' => '19.60755',
                'codigopostal' => '55064',
                'colonia' => null,
                'municipio' => 'Ecatepec de Morelos',
                'estado' => 'México',
                'regular' => 16.32,
                'premium' => 18.2,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f27',
                'calle' => 'Av. México No. 788  Col. San José  Tepic',
                'rfc' => 'GOC9303301F4',
                'razonsocial' => 'GRUPO OCTANO  S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.827Z',
                'numeropermiso' => 'PL/417/EXP/ES/2015',
                'fechaaplicacion' => '07/01/2017 01 => 35 => 00 p. m.',
                'permisoid' => '2095',
                'longitude' => '-104.8868',
                'latitude' => '21.52222',
                'codigopostal' => '63030',
                'colonia' => null,
                'municipio' => 'Tepic',
                'estado' => 'Nayarit',
                'regular' => 16.33,
                'premium' => 18.1,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f28',
                'calle' => 'Av.  Recursos Hidráulicos No. 240  Colonia San Pablo de las Salinas  Tultitlan',
                'rfc' => 'ICT050822I5A',
                'razonsocial' => 'Inmobiliaria Corredor Tultitlán  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.827Z',
                'numeropermiso' => 'PL/820/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2096',
                'longitude' => '-99.10838',
                'latitude' => '19.67871',
                'codigopostal' => '54932',
                'colonia' => null,
                'municipio' => 'Tultitlán',
                'estado' => 'México',
                'regular' => 16.32,
                'premium' => 18.2,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f29',
                'calle' => 'Avenida Tecnológico No. 4728  Colonia Puente de San Cayetano  Tepic ',
                'rfc' => 'GOC9303301F4',
                'razonsocial' => 'GRUPO OCTANO  S.A. DE C.V',
                'date_insert' => '2017-01-18T19 => 09 => 26.827Z',
                'numeropermiso' => 'PL/373/EXP/ES/2015',
                'fechaaplicacion' => '07/01/2017 01 => 42 => 00 p. m.',
                'permisoid' => '2099',
                'longitude' => '-104.8489',
                'latitude' => '21.47011',
                'codigopostal' => '63194',
                'colonia' => null,
                'municipio' => 'Tepic',
                'estado' => 'Nayarit',
                'regular' => 16.33,
                'premium' => null,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f2a',
                'calle' => 'Avenida Tecnológico No. 4728  Colonia Puente de San Cayetano  Tepic ',
                'rfc' => 'GOC9303301F4',
                'razonsocial' => 'GRUPO OCTANO  S.A. DE C.V',
                'date_insert' => '2017-01-18T19 => 09 => 26.827Z',
                'numeropermiso' => 'PL/373/EXP/ES/2015',
                'fechaaplicacion' => '07/01/2017 01 => 43 => 00 p. m.',
                'permisoid' => '2099',
                'longitude' => '-104.8489',
                'latitude' => '21.47011',
                'codigopostal' => '63194',
                'colonia' => null,
                'municipio' => 'Tepic',
                'estado' => 'Nayarit',
                'regular' => null,
                'premium' => 18.1,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f2b',
                'calle' => 'KM. 11.2 Carretera Colima - Manzanillo  Col. Centro  Colima',
                'rfc' => 'CGO960401N42',
                'razonsocial' => 'CRUCERO LAS GOLONDRINAS  S. A. DE C. V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.828Z',
                'numeropermiso' => 'PL/892/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2101',
                'longitude' => '-103.7721',
                'latitude' => '19.14014',
                'codigopostal' => '28000',
                'colonia' => null,
                'municipio' => 'Colima',
                'estado' => 'Colima',
                'regular' => 16.14,
                'premium' => 17.9,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f2c',
                'calle' => 'Blvd. Gustavo Díaz Ordaz No. 15260 Col. Benton',
                'rfc' => 'BOP970701TK2',
                'razonsocial' => 'BECKTROP OPERADORA S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.828Z',
                'numeropermiso' => 'PL/707/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2102',
                'longitude' => '-116.953',
                'latitude' => '32.49127',
                'codigopostal' => '22115',
                'colonia' => null,
                'municipio' => 'Tijuana',
                'estado' => 'Baja California',
                'regular' => 16.04,
                'premium' => 17.81,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f2d',
                'calle' => 'Juárez No. 13 Ote. C.P. 63740  Col. Centro Minicipio San Blas',
                'rfc' => 'GOC9303301F4',
                'razonsocial' => 'GRUPO OCTANO  S.A. DE C.V',
                'date_insert' => '2017-01-18T19 => 09 => 26.829Z',
                'numeropermiso' => 'PL/365/EXP/ES/2015',
                'fechaaplicacion' => '07/01/2017 01 => 28 => 00 p. m.',
                'permisoid' => '2105',
                'longitude' => '-105.2828',
                'latitude' => '21.54249',
                'codigopostal' => '63740',
                'colonia' => null,
                'municipio' => 'San Blas',
                'estado' => 'Nayarit',
                'regular' => 16.33,
                'premium' => 18.1,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f2e',
                'calle' => 'Av. Aguascalientes No.782  Col. Centro Comercial Agropecuario  Aguascalientes ',
                'rfc' => 'ESA9610146X9',
                'razonsocial' => 'ESTACIÓN DE SERVICIO AUTOMOTRÍZ DEL NORTE S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.829Z',
                'numeropermiso' => 'PL/845/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2106',
                'longitude' => '-102.2924',
                'latitude' => '21.91625',
                'codigopostal' => '20135',
                'colonia' => null,
                'municipio' => 'Aguascalientes',
                'estado' => 'Aguascalientes',
                'regular' => 16.16,
                'premium' => 17.93,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f2f',
                'calle' => 'H. Colegio Militar No.490  Col. 11 De Octubre  Acuña ',
                'rfc' => 'SCI090430KU1',
                'razonsocial' => 'SERVICIO CIBOLA  S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.829Z',
                'numeropermiso' => 'PL/685/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2107',
                'longitude' => '-100.9351',
                'latitude' => '29.30929',
                'codigopostal' => '26200',
                'colonia' => null,
                'municipio' => 'Acuña',
                'estado' => 'Coahuila de Zaragoza',
                'regular' => 16.46,
                'premium' => 18.22,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f30',
                'calle' => 'Emiliano Zapata No. 505  Col. Centro  San José de Gracia',
                'rfc' => 'MSI990615HX7',
                'razonsocial' => 'MULTISERVICIOS SIGAS  S. A. DE C. V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.829Z',
                'numeropermiso' => 'PL/655/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2109',
                'longitude' => '-102.4106',
                'latitude' => '22.14957',
                'codigopostal' => '20500',
                'colonia' => null,
                'municipio' => 'San José de Gracia',
                'estado' => 'Aguascalientes',
                'regular' => 16.16,
                'premium' => 17.93,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f31',
                'calle' => 'Boulevard Adolfo Ruíz Cortines No. 7-A  Colonia Paraíso Avícola  Atizapán de Zaragoza',
                'rfc' => 'SVA980915HL8',
                'razonsocial' => 'Servicio Vega Atizapán  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.831Z',
                'numeropermiso' => 'PL/879/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2112',
                'longitude' => '-99.25086',
                'latitude' => '19.55827',
                'codigopostal' => '52965',
                'colonia' => null,
                'municipio' => 'Atizapán de Zaragoza',
                'estado' => 'México',
                'regular' => 16.27,
                'premium' => 18.14,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f32',
                'calle' => 'Calz. Miguel Hidalgo No. 110  Col. Centro  Silao',
                'rfc' => 'SCH101001KK3',
                'razonsocial' => 'SERVICIO DEL CENTRO HIDALGO  S.A. DE C.V. ',
                'date_insert' => '2017-01-18T19 => 09 => 26.840Z',
                'numeropermiso' => 'PL/774/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2123',
                'longitude' => '-101.4349',
                'latitude' => '20.94723',
                'codigopostal' => '36100',
                'colonia' => null,
                'municipio' => 'Silao de la Victoria',
                'estado' => 'Guanajuato',
                'regular' => 16.14,
                'premium' => 17.92,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f33',
                'calle' => 'Matamoros No. 833  Col. El Pueblo  Monclova',
                'rfc' => 'ACL921020QKA',
                'razonsocial' => 'AMC COMBUSTIBLES Y LUBRICANTES  S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.842Z',
                'numeropermiso' => 'PL/779/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2125',
                'longitude' => '-101.4206',
                'latitude' => '26.91485',
                'codigopostal' => '25730',
                'colonia' => null,
                'municipio' => 'Monclova',
                'estado' => 'Coahuila de Zaragoza',
                'regular' => 16.03,
                'premium' => 17.8,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f34',
                'calle' => 'Carretera a Cd.Acuña Km. 2  Colonia San José  Piedras Negras',
                'rfc' => 'SRA9502011E3',
                'razonsocial' => 'SERVICIO RAMA  S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.843Z',
                'numeropermiso' => 'PL/796/EXP/ES/2015',
                'fechaaplicacion' => '09/01/2017 09 => 04 => 00 p. m.',
                'permisoid' => '2126',
                'longitude' => '-100.5448',
                'latitude' => '28.70405',
                'codigopostal' => '26069',
                'colonia' => null,
                'municipio' => 'Piedras Negras',
                'estado' => 'Coahuila de Zaragoza',
                'regular' => 13.26,
                'premium' => null,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f35',
                'calle' => 'Carretera a Cd.Acuña Km. 2  Colonia San José  Piedras Negras',
                'rfc' => 'SRA9502011E3',
                'razonsocial' => 'SERVICIO RAMA  S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.843Z',
                'numeropermiso' => 'PL/796/EXP/ES/2015',
                'fechaaplicacion' => '09/01/2017 09 => 06 => 00 p. m.',
                'permisoid' => '2126',
                'longitude' => '-100.5448',
                'latitude' => '28.70405',
                'codigopostal' => '26069',
                'colonia' => null,
                'municipio' => 'Piedras Negras',
                'estado' => 'Coahuila de Zaragoza',
                'regular' => null,
                'premium' => 16.03,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f36',
                'calle' => 'Carretera a Cd.Acuña Km. 2  Colonia San José  Piedras Negras',
                'rfc' => 'SRA9502011E3',
                'razonsocial' => 'SERVICIO RAMA  S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.843Z',
                'numeropermiso' => 'PL/796/EXP/ES/2015',
                'fechaaplicacion' => '09/01/2017 09 => 10 => 00 p. m.',
                'permisoid' => '2126',
                'longitude' => '-100.5448',
                'latitude' => '28.70405',
                'codigopostal' => '26069',
                'colonia' => null,
                'municipio' => 'Piedras Negras',
                'estado' => 'Coahuila de Zaragoza',
                'regular' => null,
                'premium' => null,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f37',
                'calle' => 'C. Punta El Diablo No. 19452 Col Ampliación Guaycura',
                'rfc' => 'SRA0910024E0',
                'razonsocial' => 'Servicio Ravello  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.843Z',
                'numeropermiso' => 'PL/792/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2128',
                'longitude' => '-116.9161',
                'latitude' => '32.49855',
                'codigopostal' => '22214',
                'colonia' => null,
                'municipio' => 'Tijuana',
                'estado' => 'Baja California',
                'regular' => 16.04,
                'premium' => 17.81,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f38',
                'calle' => 'Avenida Aguascalientes Ote. No. 2074  Fracc. Lomas de Santa Anita  Aguascalientes',
                'rfc' => 'MES030710P8A',
                'razonsocial' => 'MARA ESTACIÓN DE SERVICIOS  S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.843Z',
                'numeropermiso' => 'PL/766/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2133',
                'longitude' => '-102.2631',
                'latitude' => '21.89202',
                'codigopostal' => '20164',
                'colonia' => null,
                'municipio' => 'Aguascalientes',
                'estado' => 'Aguascalientes',
                'regular' => 16.16,
                'premium' => 17.93,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f39',
                'calle' => 'Boulevard Tepic Xalisco No. 142  Col. Peñitas  Tepic',
                'rfc' => 'GOC9303301F4',
                'razonsocial' => 'GRUPO OCTANO  S.A. DE C.V',
                'date_insert' => '2017-01-18T19 => 09 => 26.843Z',
                'numeropermiso' => 'PL/617/EXP/ES/2015',
                'fechaaplicacion' => '07/01/2017 01 => 35 => 00 p. m.',
                'permisoid' => '2134',
                'longitude' => '-104.8968',
                'latitude' => '21.49442',
                'codigopostal' => '63167',
                'colonia' => null,
                'municipio' => 'Tepic',
                'estado' => 'Nayarit',
                'regular' => 16.33,
                'premium' => 18.1,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f3a',
                'calle' => 'Carretera Nacional Victoria –Monterrey  Km 9.5 904 Col. Ejido  Laborcitas  Victoria ',
                'rfc' => 'SOR9704088C3',
                'razonsocial' => 'SERVICIO OROZCO S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.844Z',
                'numeropermiso' => 'PL/713/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2135',
                'longitude' => '-99.12276',
                'latitude' => '23.82137',
                'codigopostal' => '87261',
                'colonia' => null,
                'municipio' => 'Victoria',
                'estado' => 'Tamaulipas',
                'regular' => 15.64,
                'premium' => 17.41,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f3b',
                'calle' => 'Av. Ignacio Sandoval No. 1555  Colonia Girasoles  Colima',
                'rfc' => 'SPH1009157E8',
                'razonsocial' => 'SERVICIO PUERTA DE HIERRO S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.844Z',
                'numeropermiso' => 'PL/770/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2136',
                'longitude' => '-103.7087',
                'latitude' => '19.25796',
                'codigopostal' => '28018',
                'colonia' => null,
                'municipio' => 'Colima',
                'estado' => 'Colima',
                'regular' => 16.14,
                'premium' => 17.9,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f3c',
                'calle' => 'Av. Central  Lt. 1 Mz-A s/n Las Américas  Ecatepec',
                'rfc' => 'GRM031203B76',
                'razonsocial' => 'Gasolinería Real Madeira  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.844Z',
                'numeropermiso' => 'PL/835/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2137',
                'longitude' => '-99.02091',
                'latitude' => '19.57863',
                'codigopostal' => '55070',
                'colonia' => null,
                'municipio' => 'Ecatepec de Morelos',
                'estado' => 'México',
                'regular' => 16.32,
                'premium' => 18.2,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f3d',
                'calle' => 'Carretera Nacional Visitación N° 45 Colonia Visitación. Municipio Melchor Ocampo',
                'rfc' => 'ISO101220C96',
                'razonsocial' => 'Inmobiliaria Socor  S.A. de C.V. ',
                'date_insert' => '2017-01-18T19 => 09 => 26.844Z',
                'numeropermiso' => 'PL/630/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2140',
                'longitude' => '-99.13939',
                'latitude' => '19.71715',
                'codigopostal' => '54890',
                'colonia' => null,
                'municipio' => 'Melchor Ocampo',
                'estado' => 'México',
                'regular' => 16.27,
                'premium' => 18.14,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f3e',
                'calle' => 'Calz. Manuel Gómez Morin y Calle de los Portales  Fracc. Hacienda de los Portales  Mexicali',
                'rfc' => 'GEC030808DD6',
                'razonsocial' => 'Grupo Empresarial Cachanilla  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.844Z',
                'numeropermiso' => 'PL/394/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2141',
                'longitude' => '-115.5029',
                'latitude' => '32.59509',
                'codigopostal' => '21327',
                'colonia' => null,
                'municipio' => 'Mexicali',
                'estado' => 'Baja California',
                'regular' => 16.17,
                'premium' => 17.95,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f3f',
                'calle' => 'Avenida Valle Escondido No. 21. Colonia Loma Linda  1 Sección  Atizapán de Zaragoza',
                'rfc' => 'GIT1006044MA',
                'razonsocial' => 'Gasolinería Itálica  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.844Z',
                'numeropermiso' => 'PL/632/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2142',
                'longitude' => '-99.2491',
                'latitude' => '19.53231',
                'codigopostal' => '52949',
                'colonia' => null,
                'municipio' => 'Atizapán de Zaragoza',
                'estado' => 'México',
                'regular' => 16.27,
                'premium' => 18.14,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f40',
                'calle' => 'Autopista México - Acapulco   Lado A km 92.600  Acapantzingo  Cuernavaca',
                'rfc' => 'SSC990310GI1',
                'razonsocial' => 'Súper Servicio Cumbre  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.845Z',
                'numeropermiso' => 'PL/853/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2143',
                'longitude' => '-99.21558',
                'latitude' => '18.90457',
                'codigopostal' => '62440',
                'colonia' => null,
                'municipio' => 'Cuernavaca',
                'estado' => 'Morelos',
                'regular' => 15.93,
                'premium' => 17.7,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f41',
                'calle' => 'Carr. Dolores Hidalgo - San Luis de la Paz Km. 5 S/C  Dolores Hidalgo Cuna de la Independencia Nacional',
                'rfc' => 'ESC140515GM0',
                'razonsocial' => 'ESTACIONES DE SERVICIO CAMINOS DE GUANAJUATO  S. A. DE C. V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.845Z',
                'numeropermiso' => 'PL/893/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2144',
                'longitude' => '-100.9016',
                'latitude' => '21.16531',
                'codigopostal' => '37800',
                'colonia' => null,
                'municipio' => 'Dolores Hidalgo Cuna de la Independencia Nacional',
                'estado' => 'Guanajuato',
                'regular' => 16.09,
                'premium' => 17.86,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f42',
                'calle' => 'Del circuito de frutas y verduras Manzana 11 Lote 11 Colonia Central de Abastos Delegacion Iztapalapa',
                'rfc' => 'IRA080924757',
                'razonsocial' => 'Inmobiliaria Ravs  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.846Z',
                'numeropermiso' => 'PL/695/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2153',
                'longitude' => '-99.08196',
                'latitude' => '19.37504',
                'codigopostal' => '9040',
                'colonia' => null,
                'municipio' => 'Iztapalapa',
                'estado' => 'Ciudad de México',
                'regular' => 16.32,
                'premium' => 18.2,
                'dieasel' => null,
            ],
            [
                'id' => '587fbd68edfe99480a072f43',
                'calle' => 'Carretera Tecpatan Raudales Malpaso km 4.23 s/n Predio La Bondad  Raudales Malpaso',
                'rfc' => 'GLM041206SP4',
                'razonsocial' => 'GASOLINA Y LUBRICANTES MALPASO S.A. DE C.V.  ',
                'date_insert' => '2017-01-18T19 => 09 => 26.846Z',
                'numeropermiso' => 'PL/725/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2154',
                'longitude' => '-93.56612',
                'latitude' => '17.18763',
                'codigopostal' => '29600',
                'colonia' => null,
                'municipio' => 'Mezcalapa',
                'estado' => 'Chiapas',
                'regular' => 15.73,
                'premium' => 17.5,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f44',
                'calle' => 'Avenida Hidalgo No. 83  Colonia San Miguel Ajusco  Tlalpan',
                'rfc' => 'GMG07041091A',
                'razonsocial' => 'Gasolinería México Ajusco 1 S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.846Z',
                'numeropermiso' => 'PL/821/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2157',
                'longitude' => '-99.19692',
                'latitude' => '19.2289',
                'codigopostal' => '14700',
                'colonia' => null,
                'municipio' => 'Tlalpan',
                'estado' => 'Ciudad de México',
                'regular' => 16.33,
                'premium' => 18.2,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f45',
                'calle' => 'Av. Venustiano Carranza y Calle 4ta No.400 Colonia Comercial',
                'rfc' => 'GEC030808DD6',
                'razonsocial' => 'Grupo Empresarial Cachanilla  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.846Z',
                'numeropermiso' => 'PL/383/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2160',
                'longitude' => '-114.7834',
                'latitude' => '32.47077',
                'codigopostal' => '83449',
                'colonia' => null,
                'municipio' => 'San Luis Río Colorado',
                'estado' => 'Sonora',
                'regular' => 16.17,
                'premium' => 17.95,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f46',
                'calle' => 'Insurgentes No. 45  La Barranca Panuaya  Tezontepec De Aldama',
                'rfc' => 'EST081124IZA',
                'razonsocial' => 'ESTACIÓN DE SERVICIO TEZONTEPEC S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.847Z',
                'numeropermiso' => 'PL/719/EXP/ES/2015',
                'fechaaplicacion' => '09/01/2017 09 => 45 => 00 p. m.',
                'permisoid' => '2163',
                'longitude' => '-99.26816',
                'latitude' => '20.19257',
                'codigopostal' => '42760',
                'colonia' => null,
                'municipio' => 'Tezontepec de Aldama',
                'estado' => 'Hidalgo',
                'regular' => 15.83,
                'premium' => 17.6,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f47',
                'calle' => 'Calle 10 de Abril No. 711  Colonia Granjas  Cuernavaca',
                'rfc' => 'ESC080311HB2',
                'razonsocial' => 'Estación de Servicio Córdoba S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.848Z',
                'numeropermiso' => 'PL/664/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2165',
                'longitude' => '-99.20078',
                'latitude' => '18.91205',
                'codigopostal' => '62460',
                'colonia' => null,
                'municipio' => 'Cuernavaca',
                'estado' => 'Morelos',
                'regular' => 15.93,
                'premium' => 17.7,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f48',
                'calle' => 'Cuauhtémoc sur poniente No. 2834 Col. Dávila',
                'rfc' => 'BOP970701TK2',
                'razonsocial' => 'BECKTROP OPERADORA S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.849Z',
                'numeropermiso' => 'PL/702/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2166',
                'longitude' => '-117.0214',
                'latitude' => '32.51695',
                'codigopostal' => '22044',
                'colonia' => null,
                'municipio' => 'Tijuana',
                'estado' => 'Baja California',
                'regular' => 16.04,
                'premium' => 17.81,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f49',
                'calle' => 'Calzada Gustavo Vildosola Castro No.1901  Colonia Ex Ejido Coahuila',
                'rfc' => 'GEC030808DD6',
                'razonsocial' => 'GRUPO EMPRESARIAL CACHANILLA  S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.849Z',
                'numeropermiso' => 'PL/378/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2167',
                'longitude' => '-115.4283',
                'latitude' => '32.60439',
                'codigopostal' => '21360',
                'colonia' => null,
                'municipio' => 'Mexicali',
                'estado' => 'Baja California',
                'regular' => 16.17,
                'premium' => 17.95,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f4a',
                'calle' => 'Av. Ignacio Zaragoza y Av. Cascada  La Balsa  Fracc. Valle de Puebla VI Sección',
                'rfc' => 'GEC030808DD6',
                'razonsocial' => 'GRUPO EMPRESARIAL CACHANILLA  S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.849Z',
                'numeropermiso' => 'PL/393/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2173',
                'longitude' => '-115.3589',
                'latitude' => '32.55959',
                'codigopostal' => '21395',
                'colonia' => null,
                'municipio' => 'Mexicali',
                'estado' => 'Baja California',
                'regular' => 16.17,
                'premium' => 17.95,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f4b',
                'calle' => 'Calz. Heroica Puebla No. 18 Fracc. Ángeles de Puebla',
                'rfc' => 'GEC030808DD6',
                'razonsocial' => 'Grupo Empresarial Cachanilla  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.849Z',
                'numeropermiso' => 'PL/384/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2174',
                'longitude' => '0',
                'latitude' => '0',
                'codigopostal' => '21620',
                'colonia' => null,
                'municipio' => 'Mexicali',
                'estado' => 'Baja California',
                'regular' => 16.17,
                'premium' => 17.95,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f4c',
                'calle' => 'Blvd. Luis Donaldo Colosio No. 814  Col. Benito Juárez Ote. Tepic',
                'rfc' => 'CEX9809213U5',
                'razonsocial' => 'COMBU-EXPRESS  S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.850Z',
                'numeropermiso' => 'PL/769/EXP/ES/2015',
                'fechaaplicacion' => '09/01/2017 09 => 29 => 00 a. m.',
                'permisoid' => '2180',
                'longitude' => '-103.2836',
                'latitude' => '20.5629',
                'codigopostal' => '63166',
                'colonia' => null,
                'municipio' => 'Tepic',
                'estado' => 'Nayarit',
                'regular' => 16.33,
                'premium' => 18.1,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f4d',
                'calle' => 'Carr. Texcoco-Lechería s/n  Colonia  Santa María Chiconaulta  Ecatepec',
                'rfc' => 'SJA020619D49',
                'razonsocial' => 'Servicio Jacarandas  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.850Z',
                'numeropermiso' => 'PL/854/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2182',
                'longitude' => '-99.0181',
                'latitude' => '19.61462',
                'codigopostal' => '55066',
                'colonia' => null,
                'municipio' => 'Ecatepec de Morelos',
                'estado' => 'México',
                'regular' => 16.32,
                'premium' => 18.2,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f4e',
                'calle' => 'Camino a San Andrés Lote 2 No. 21 Colonia Carlos Hank González  Ecatepec',
                'rfc' => 'ESM030311CT0',
                'razonsocial' => 'Estación de Servicio Marbella  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.850Z',
                'numeropermiso' => 'PL/692/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2186',
                'longitude' => '-99.07384',
                'latitude' => '19.54896',
                'codigopostal' => '55520',
                'colonia' => null,
                'municipio' => 'Ecatepec de Morelos',
                'estado' => 'México',
                'regular' => 16.32,
                'premium' => 18.2,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f4f',
                'calle' => 'Cisnes N°40 Manzana 10 Lote 13 y 14  Colonia Lago de Guadalupe. Cuautitlán Izcalli',
                'rfc' => 'GUL0911187N6',
                'razonsocial' => 'Gasolinaría Ulises  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.850Z',
                'numeropermiso' => 'PL/648/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2188',
                'longitude' => '-99.2403',
                'latitude' => '19.62737',
                'codigopostal' => '54760',
                'colonia' => null,
                'municipio' => 'Cuautitlán Izcalli',
                'estado' => 'México',
                'regular' => 16.27,
                'premium' => 18.14,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f50',
                'calle' => 'Boulevard Adolfo López Mateos No. 206 Col. Loma del Gallo',
                'rfc' => 'ESC0805285M4',
                'razonsocial' => 'Estación de Servicio Cuenca S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.850Z',
                'numeropermiso' => 'PL/693/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2191',
                'longitude' => '-97.85314',
                'latitude' => '22.254',
                'codigopostal' => '89460',
                'colonia' => null,
                'municipio' => 'Ciudad Madero',
                'estado' => 'Tamaulipas',
                'regular' => 15.37,
                'premium' => 17.14,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f51',
                'calle' => 'Av. San Gabriel No. 707  Fracc. Ojocaliente III',
                'rfc' => 'DAL0903263K3',
                'razonsocial' => 'DALROM  S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.850Z',
                'numeropermiso' => 'PL/757/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2193',
                'longitude' => '-99.72745',
                'latitude' => '19.2539',
                'codigopostal' => '20196',
                'colonia' => null,
                'municipio' => 'Aguascalientes',
                'estado' => 'Aguascalientes',
                'regular' => 16.16,
                'premium' => 17.93,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f52',
                'calle' => 'Calzada de la Quinta No.227  Barrio la Garita  San Cristóbal de las Casas',
                'rfc' => 'CAR120703944',
                'razonsocial' => 'COMBUSTIBLES ARCOTETE  S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.850Z',
                'numeropermiso' => 'PL/735/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2195',
                'longitude' => '-92.60492',
                'latitude' => '16.73734',
                'codigopostal' => '29230',
                'colonia' => null,
                'municipio' => 'San Cristóbal de las Casas',
                'estado' => 'Chiapas',
                'regular' => 15.73,
                'premium' => 17.5,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f53',
                'calle' => 'Camino a España No. 351-A  Colonia Barrio de Santiago Segunda Sección  Zumpango',
                'rfc' => 'ESR100226HBA',
                'razonsocial' => 'Estación de Servicio La Rioja S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.850Z',
                'numeropermiso' => 'PL/647/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2196',
                'longitude' => '-99.08937',
                'latitude' => '19.82526',
                'codigopostal' => '55600',
                'colonia' => null,
                'municipio' => 'Zumpango',
                'estado' => 'México',
                'regular' => 15.79,
                'premium' => 17.56,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f54',
                'calle' => 'Blvd. Jesús Valdes Sánchez No. 2911  Colonia El Toreo  Saltillo',
                'rfc' => 'sts060503826',
                'razonsocial' => 'SERVICIO EL TOREO DE SALTILLO S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.851Z',
                'numeropermiso' => 'PL/771/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2197',
                'longitude' => '-100.9147',
                'latitude' => '25.44261',
                'codigopostal' => '25298',
                'colonia' => null,
                'municipio' => 'Saltillo',
                'estado' => 'Coahuila de Zaragoza',
                'regular' => 15.98,
                'premium' => 17.75,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f55',
                'calle' => 'Av. Rafael Pérez Serna No. 676  Col. Partido Romero  Juárez',
                'rfc' => 'DGA930823KD3',
                'razonsocial' => 'DÍAZ GAS  S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.851Z',
                'numeropermiso' => 'PL/761/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2200',
                'longitude' => '-106.4253',
                'latitude' => '31.7462',
                'codigopostal' => '32330',
                'colonia' => null,
                'municipio' => 'Juárez',
                'estado' => 'Chihuahua',
                'regular' => 15.71,
                'premium' => 17.93,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f56',
                'calle' => 'Av. Insurgentes 1131 ote.  Col. Las Aves  Tepic',
                'rfc' => 'GOC9303301F4',
                'razonsocial' => 'GRUPO OCTANO  S.A. DE C.V',
                'date_insert' => '2017-01-18T19 => 09 => 26.851Z',
                'numeropermiso' => 'PL/416/EXP/ES/2015',
                'fechaaplicacion' => '07/01/2017 01 => 35 => 00 p. m.',
                'permisoid' => '2208',
                'longitude' => '-104.883',
                'latitude' => '21.49595',
                'codigopostal' => '63170',
                'colonia' => null,
                'municipio' => 'Tepic',
                'estado' => 'Nayarit',
                'regular' => 16.33,
                'premium' => 18.1,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f57',
                'calle' => 'Carretera a los Planes No.3650 ',
                'rfc' => 'GPA0610318A0',
                'razonsocial' => 'GASOLINERAS PABA S.A. DE C.V. ',
                'date_insert' => '2017-01-18T19 => 09 => 26.852Z',
                'numeropermiso' => 'PL/733/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2209',
                'longitude' => '-110.2945',
                'latitude' => '24.12212',
                'codigopostal' => '23050',
                'colonia' => null,
                'municipio' => 'La Paz',
                'estado' => 'Baja California Sur',
                'regular' => 16,
                'premium' => 17.76,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f58',
                'calle' => 'Calz. De Jesuita Agustín de Espinoza no. 1011  Col. Aviación  Torreón',
                'rfc' => 'SGA070326I33',
                'razonsocial' => 'Servicio Gasol  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.852Z',
                'numeropermiso' => 'PL/883/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2210',
                'longitude' => '-103.3947',
                'latitude' => '25.55813',
                'codigopostal' => '27050',
                'colonia' => null,
                'municipio' => 'Torreón',
                'estado' => 'Coahuila de Zaragoza',
                'regular' => 16.13,
                'premium' => 17.9,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f59',
                'calle' => 'Blvd. Agua Caliente No. 9150  Col Marrón',
                'rfc' => 'BOP970701TK2',
                'razonsocial' => 'BECKTROP OPERADORA S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.852Z',
                'numeropermiso' => 'PL/709/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2212',
                'longitude' => '-117.0259',
                'latitude' => '32.52285',
                'codigopostal' => '22015',
                'colonia' => null,
                'municipio' => 'Tijuana',
                'estado' => 'Baja California',
                'regular' => 16.04,
                'premium' => 17.81,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f5a',
                'calle' => 'Carretera México - Tepexpan S/N  Colonia Sta. María Chiconautla  Ecatepec',
                'rfc' => 'ESV051207AR2',
                'razonsocial' => 'Estación de Servicio Venta de Carpio  S.A.de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.853Z',
                'numeropermiso' => 'PL/819/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2214',
                'longitude' => '-99.00452',
                'latitude' => '19.6214',
                'codigopostal' => '55066',
                'colonia' => null,
                'municipio' => 'Ecatepec de Morelos',
                'estado' => 'México',
                'regular' => 16.32,
                'premium' => 18.2,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f5b',
                'calle' => '5 de Febrero No. 1215  Colonia Pueblo Nuevo',
                'rfc' => 'GPA0610318A0',
                'razonsocial' => 'GASOLINERAS PABA S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.853Z',
                'numeropermiso' => 'PL/688/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2216',
                'longitude' => '-110.314',
                'latitude' => '24.14254',
                'codigopostal' => '23060',
                'colonia' => null,
                'municipio' => 'La Paz',
                'estado' => 'Baja California Sur',
                'regular' => 16,
                'premium' => 17.76,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f5c',
                'calle' => 'Carretera Huixtla Tapachula Km. 281 Mas 656  Col. Viva México  Tapachula',
                'rfc' => 'ESO100211V84',
                'razonsocial' => 'ENERGÉTICOS Y SERVICIOS OCOZOCOAUTLA S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.853Z',
                'numeropermiso' => 'PL/765/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2218',
                'longitude' => '-92.34282',
                'latitude' => '14.91567',
                'codigopostal' => '30820',
                'colonia' => null,
                'municipio' => 'Tapachula',
                'estado' => 'Chiapas',
                'regular' => 15.95,
                'premium' => 17.72,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f5d',
                'calle' => 'Calz. Avelardo L. Rodríguez  Colonia Calles  Mexicali',
                'rfc' => 'GEC030808DD6',
                'razonsocial' => 'Grupo Empresarial Cachanilla  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.854Z',
                'numeropermiso' => 'PL/398/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2221',
                'longitude' => '-115.3744',
                'latitude' => '32.65948',
                'codigopostal' => '21226',
                'colonia' => null,
                'municipio' => 'Mexicali',
                'estado' => 'Baja California',
                'regular' => 16.17,
                'premium' => 17.95,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f5e',
                'calle' => 'Carretera Mexicali-San Felipe No.399  Colonia Dos División Dos',
                'rfc' => 'GEC030808DD6',
                'razonsocial' => 'Grupo Empresarial Cachanilla  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.854Z',
                'numeropermiso' => 'PL/389/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2222',
                'longitude' => '-115.4325',
                'latitude' => '32.59562',
                'codigopostal' => '21383',
                'colonia' => null,
                'municipio' => 'Mexicali',
                'estado' => 'Baja California',
                'regular' => 16.17,
                'premium' => 17.95,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f5f',
                'calle' => 'Lote 1 Manzana 28 de la Zona 1 Ejido Nueva Orizaba  Benemérito de las Americas',
                'rfc' => 'DCC050516VD1',
                'razonsocial' => 'DISTRIBUIDORA DE COMBUSTIBLES LAS CAÑADAS S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.854Z',
                'numeropermiso' => 'PL/739/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2226',
                'longitude' => '-90.63845',
                'latitude' => '16.08285',
                'codigopostal' => '29955',
                'colonia' => null,
                'municipio' => 'Benemérito de las Américas',
                'estado' => 'Chiapas',
                'regular' => 16.1,
                'premium' => 17.87,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f60',
                'calle' => 'Blvd. Isidro López Zertuche No. 5851  Col. Brisas  Saltillo',
                'rfc' => 'seb9606121d9',
                'razonsocial' => 'SERVICIOS ENERGÉTICOS BRISAS S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.855Z',
                'numeropermiso' => 'PL/741/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2227',
                'longitude' => '-100.9835',
                'latitude' => '25.48155',
                'codigopostal' => '25169',
                'colonia' => null,
                'municipio' => 'Saltillo',
                'estado' => 'Coahuila de Zaragoza',
                'regular' => 15.98,
                'premium' => 17.75,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f61',
                'calle' => 'Blvd. Gustavo DÍaz Ordaz No. 15260 Col. Benton',
                'rfc' => 'BOP970701TK2',
                'razonsocial' => 'BECKTROP OPERADORA S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.855Z',
                'numeropermiso' => 'PL/716/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2230',
                'longitude' => '-115.472',
                'latitude' => '32.65055',
                'codigopostal' => '22115',
                'colonia' => null,
                'municipio' => 'Tijuana',
                'estado' => 'Baja California',
                'regular' => 16.17,
                'premium' => 17.95,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f62',
                'calle' => 'Libramiento Poniente  s/n Ocozocoautla de Espinosa ',
                'rfc' => 'GLC000915431',
                'razonsocial' => 'GASOLINERIA LAZARO CHANONA BORGES S.A. DE C.V. ',
                'date_insert' => '2017-01-18T19 => 09 => 26.855Z',
                'numeropermiso' => 'PL/777/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2231',
                'longitude' => '-93.38528',
                'latitude' => '16.76469',
                'codigopostal' => '29140',
                'colonia' => null,
                'municipio' => 'Ocozocoautla de Espinosa',
                'estado' => 'Chiapas',
                'regular' => 15.73,
                'premium' => 17.5,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f63',
                'calle' => 'Av. Oaxaca s/n  Col. La Cooperativa  Benemérito de las Americas',
                'rfc' => 'DCC050516VD1',
                'razonsocial' => 'DISTRIBUIDORA DE COMBUSTIBLES LAS CAÑADAS S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.856Z',
                'numeropermiso' => 'PL/736/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2234',
                'longitude' => '-90.65433',
                'latitude' => '16.50013',
                'codigopostal' => '29955',
                'colonia' => null,
                'municipio' => 'Benemérito de las Américas',
                'estado' => 'Chiapas',
                'regular' => 16.1,
                'premium' => 17.87,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f64',
                'calle' => 'Av. Par Vía Jiutepec No. 44  Colonia Atlacomulco  Jiutepec',
                'rfc' => 'ESC0312037U6',
                'razonsocial' => 'Estación de Servicio Cantabria  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.856Z',
                'numeropermiso' => 'PL/822/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2236',
                'longitude' => '-99.19987',
                'latitude' => '18.88947',
                'codigopostal' => '62560',
                'colonia' => null,
                'municipio' => 'Jiutepec',
                'estado' => 'Morelos',
                'regular' => 15.93,
                'premium' => 17.7,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f65',
                'calle' => 'Carretera Colonia Progreso - Santa Isabel s/n Fracc. Valle del Progreso',
                'rfc' => 'GEC030808DD6',
                'razonsocial' => 'Grupo Empresarial Cachanilla  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.857Z',
                'numeropermiso' => 'PL/403/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2240',
                'longitude' => '-115.5797',
                'latitude' => '32.58874',
                'codigopostal' => '21326',
                'colonia' => null,
                'municipio' => 'Mexicali',
                'estado' => 'Baja California',
                'regular' => 16.17,
                'premium' => 17.95,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f66',
                'calle' => 'Av. Colón No.1870  Colonia del Fresno  Guadalajara',
                'rfc' => 'GCO740121MC5',
                'razonsocial' => 'GASOLINERA COLÓN S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.857Z',
                'numeropermiso' => 'PL/828/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2243',
                'longitude' => '-103.3658',
                'latitude' => '20.65207',
                'codigopostal' => '44900',
                'colonia' => null,
                'municipio' => 'Guadalajara',
                'estado' => 'Jalisco',
                'regular' => 16.52,
                'premium' => 18.4,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f67',
                'calle' => 'Av. Insurgentes No. 2795 Oriente  Col. Lagos del Country  Tepic',
                'rfc' => 'GOC9303301F4',
                'razonsocial' => 'GRUPO OCTANO  S.A. DE C.V',
                'date_insert' => '2017-01-18T19 => 09 => 26.858Z',
                'numeropermiso' => 'PL/363/EXP/ES/2015',
                'fechaaplicacion' => '07/01/2017 01 => 38 => 00 p. m.',
                'permisoid' => '2245',
                'longitude' => '-104.8595',
                'latitude' => '21.47486',
                'codigopostal' => '63197',
                'colonia' => null,
                'municipio' => 'Tepic',
                'estado' => 'Nayarit',
                'regular' => 16.33,
                'premium' => null,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f68',
                'calle' => 'Av. Insurgentes No. 2795 Oriente  Col. Lagos del Country  Tepic',
                'rfc' => 'GOC9303301F4',
                'razonsocial' => 'GRUPO OCTANO  S.A. DE C.V',
                'date_insert' => '2017-01-18T19 => 09 => 26.858Z',
                'numeropermiso' => 'PL/363/EXP/ES/2015',
                'fechaaplicacion' => '07/01/2017 01 => 39 => 00 p. m.',
                'permisoid' => '2245',
                'longitude' => '-104.8595',
                'latitude' => '21.47486',
                'codigopostal' => '63197',
                'colonia' => null,
                'municipio' => 'Tepic',
                'estado' => 'Nayarit',
                'regular' => null,
                'premium' => 18.1,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f69',
                'calle' => 'Libramiento Manuel Pérez Treviño No. 300  Don Antonio',
                'rfc' => 'OCR950306RV3',
                'razonsocial' => 'OPERADORA LAS CRUCES S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.858Z',
                'numeropermiso' => 'PL/791/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2248',
                'longitude' => '-100.5463',
                'latitude' => '28.70271',
                'codigopostal' => '26069',
                'colonia' => null,
                'municipio' => 'Piedras Negras',
                'estado' => 'Coahuila de Zaragoza',
                'regular' => 16.13,
                'premium' => 17.9,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f6a',
                'calle' => 'Blvd. Benito Juarez No. 490  Col. El Encanto Norte',
                'rfc' => 'EEN0203238I6',
                'razonsocial' => 'El Encanto S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.858Z',
                'numeropermiso' => 'PL/726/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2251',
                'longitude' => '-116.6503',
                'latitude' => '32.56519',
                'codigopostal' => '21447',
                'colonia' => null,
                'municipio' => 'Tecate',
                'estado' => 'Baja California',
                'regular' => 16.17,
                'premium' => 17.95,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f6b',
                'calle' => 'Calzada de los Monarcas #1198 Fracc. Residencial Villa del Rey II Etapa',
                'rfc' => 'GEC030808DD6',
                'razonsocial' => 'Grupo Empresarial Cachanilla  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.858Z',
                'numeropermiso' => 'PL/382/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2252',
                'longitude' => '-115.483',
                'latitude' => '32.59637',
                'codigopostal' => '21354',
                'colonia' => null,
                'municipio' => 'Mexicali',
                'estado' => 'Baja California',
                'regular' => 16.17,
                'premium' => 17.95,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f6c',
                'calle' => 'Av. Canal de Castera No.72  Col. Gustavo Baz',
                'rfc' => 'GTU001023FY6',
                'razonsocial' => 'Gasolinería Turquesa   S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.858Z',
                'numeropermiso' => 'PL/864/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2253',
                'longitude' => '-99.07876',
                'latitude' => '19.67295',
                'codigopostal' => '54934',
                'colonia' => null,
                'municipio' => 'Tultitlán',
                'estado' => 'México',
                'regular' => 16.32,
                'premium' => 18.2,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f6d',
                'calle' => 'Av. Municipio Libre No. 88 y Esq. Libertad  Col. Adición Sur  Juárez',
                'rfc' => 'DGA930823KD3',
                'razonsocial' => 'Díaz Gas  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.859Z',
                'numeropermiso' => 'PL/776/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2259',
                'longitude' => '-106.4733',
                'latitude' => '31.7203',
                'codigopostal' => '32000',
                'colonia' => null,
                'municipio' => 'Juárez',
                'estado' => 'Chihuahua',
                'regular' => 15.71,
                'premium' => 17.93,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f6e',
                'calle' => 'Carretera Palau - Múzquiz Km. 26 S/N  Col. Centro  Múzquiz',
                'rfc' => 'SPS920824TX4',
                'razonsocial' => 'SERVICIO PALAU  S. A. DE C. V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.859Z',
                'numeropermiso' => 'PL/673/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2264',
                'longitude' => '-101.4273',
                'latitude' => '27.88953',
                'codigopostal' => '26350',
                'colonia' => null,
                'municipio' => 'Coahuila de Zaragoza',
                'estado' => null,
                'regular' => '16.46',
                'premium' => '18.22',
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f6f',
                'calle' => 'Av. Juárez No. 245  Col. Miami',
                'rfc' => 'GDI9612186D7',
                'razonsocial' => 'GAELI DIESEL  S.A. DE C.V. ',
                'date_insert' => '2017-01-18T19 => 09 => 26.859Z',
                'numeropermiso' => 'PL/872/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2266',
                'longitude' => '-91.83187',
                'latitude' => '18.65904',
                'codigopostal' => '24115',
                'colonia' => null,
                'municipio' => 'Carmen',
                'estado' => 'Campeche',
                'regular' => 15.65,
                'premium' => 17.42,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f70',
                'calle' => 'Carretera Internacional No. 6154  Col. Plan De Ayala',
                'rfc' => 'CRC0412029S2',
                'razonsocial' => 'COMBUSTIBLES Y REPARACIONES DE CHIAPAS S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.859Z',
                'numeropermiso' => 'PL/844/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2269',
                'longitude' => '-93.1921',
                'latitude' => '16.76767',
                'codigopostal' => '29110',
                'colonia' => null,
                'municipio' => 'Tuxtla Gutiérrez',
                'estado' => 'Chiapas',
                'regular' => 15.73,
                'premium' => 17.5,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f71',
                'calle' => 'Vialidad Principal LT1 Circuitro Fruta y Legumbres  Colonia Central de Abastos  Iztapalapa',
                'rfc' => 'GA9912032ZA',
                'razonsocial' => 'Gasolinería Magnolias  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.859Z',
                'numeropermiso' => 'PL/631/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2272',
                'longitude' => '-99.09545',
                'latitude' => '19.37437',
                'codigopostal' => '9040',
                'colonia' => null,
                'municipio' => 'Iztapalapa',
                'estado' => 'Ciudad de México',
                'regular' => 16.32,
                'premium' => 18.2,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f72',
                'calle' => 'Blvd. 5 de Febrero No. 2990  Esquina Jaime Bravo  Col. Benito Juárez  La Paz',
                'rfc' => 'OCO0507069L4',
                'razonsocial' => 'OPERADORA DE COMBUSTIBLE  S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.859Z',
                'numeropermiso' => 'PL/782/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2273',
                'longitude' => '-110.2967',
                'latitude' => '24.1315',
                'codigopostal' => '23050',
                'colonia' => null,
                'municipio' => 'La Paz',
                'estado' => 'Baja California Sur',
                'regular' => 16,
                'premium' => 17.76,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f73',
                'calle' => 'Carretera 30 Km 12 No. 2000  Fracc San Antonio  Frontera',
                'rfc' => 'SOE051209QX8',
                'razonsocial' => 'SERVICIO 8 DE ENERO S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.859Z',
                'numeropermiso' => 'PL/763/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2282',
                'longitude' => '-101.4921',
                'latitude' => '26.99841',
                'codigopostal' => '25810',
                'colonia' => null,
                'municipio' => 'Frontera',
                'estado' => 'Coahuila de Zaragoza',
                'regular' => 16.03,
                'premium' => 17.8,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f74',
                'calle' => 'Lauro Rendón Norte 112 Colonia Heroe de Nacozari',
                'rfc' => 'GVE020327QL4',
                'razonsocial' => 'Gasolinera el 27 S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.859Z',
                'numeropermiso' => 'PL/703/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2283',
                'longitude' => '-99.16292',
                'latitude' => '23.73274',
                'codigopostal' => '87030',
                'colonia' => null,
                'municipio' => 'Victoria',
                'estado' => 'Tamaulipas',
                'regular' => 15.64,
                'premium' => 17.41,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f75',
                'calle' => 'Carretera Lechería Texcoco S/N  Los Héroes Tecamac Sexta Sección  Tecamac',
                'rfc' => 'ESS051207T22',
                'razonsocial' => 'Estación de Servicio Sauvage  S.A. de C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.860Z',
                'numeropermiso' => 'PL/826/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2287',
                'longitude' => '-99.02579',
                'latitude' => '19.61582',
                'codigopostal' => '55763',
                'colonia' => null,
                'municipio' => 'Tecámac',
                'estado' => 'México',
                'regular' => 16.32,
                'premium' => 18.2,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f76',
                'calle' => 'Av. Tercer Anillo Periférico No. 151  Colonia Primavera',
                'rfc' => 'GAS060322BI6',
                'razonsocial' => 'GASOPRIM S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.860Z',
                'numeropermiso' => 'PL/758/EXP/ES/2015',
                'fechaaplicacion' => null,
                'permisoid' => '2291',
                'longitude' => '-103.7026',
                'latitude' => '19.2684',
                'codigopostal' => '28015',
                'colonia' => null,
                'municipio' => 'Colima',
                'estado' => 'Colima',
                'regular' => 16.14,
                'premium' => 17.9,
                'dieasel' => null
            ],
            [
                'id' => '587fbd68edfe99480a072f77',
                'calle' => 'Libramiento Tepic-Mazatlán No. 48  Col. Rodeo de la Punta  Tepic',
                'rfc' => 'GOC9303301F4',
                'razonsocial' => 'GRUPO OCTANO  S.A. DE C.V.',
                'date_insert' => '2017-01-18T19 => 09 => 26.860Z',
                'numeropermiso' => 'PL/420/EXP/ES/2015',
                'fechaaplicacion' => '07/01/2017 01 => 35 => 00 p. m.',
                'permisoid' => '2292',
                'longitude' => '-104.9266',
                'latitude' => '21.52014',
                'codigopostal' => '63117',
                'colonia' => null,
                'municipio' => 'Tepic',
                'estado' => 'Nayarit',
                'regular' => 16.33,
                'premium' => 18.1,
                'dieasel' => null
            ]
        ]);
    }
}
